import { Zap, Target, Award, Mail } from 'lucide-react';

export default function AboutPage() {
    const siteName = "CASH COW INTELLIGENCE";
    const domain = "cashcow.news"; // Placeholder domain

    return (
        <main className="bg-[#FDFDFD] min-h-screen py-24">
            <div className="max-w-4xl mx-auto px-4">
                <header className="mb-20 border-b border-gray-100 pb-12 text-center md:text-left">
                    <div className="flex items-center justify-center md:justify-start gap-4 text-primary mb-12">
                        <div className="bg-primary p-2 rounded-lg">
                            <Zap className="text-white fill-white" size={24} />
                        </div>
                        <span className="text-sm font-black uppercase tracking-[0.3em] text-gray-900 leading-none">
                            Institutional Profile
                        </span>
                    </div>

                    <h1 className="text-6xl md:text-8xl font-black serif text-gray-900 mb-8 leading-[1.05] tracking-tight">
                        About The Capital Sentinel
                    </h1>

                    <p className="text-xl md:text-2xl text-gray-500 serif italic leading-relaxed max-w-2xl mx-auto md:mx-0">
                        Bridging the gap between raw global data and actionable strategic intelligence.
                    </p>
                </header>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-16 mb-24">
                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-primary mb-2">
                            <Target size={20} />
                            <h2 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-900 pt-0.5">Our Mission</h2>
                        </div>
                        <p className="text-lg text-gray-600 leading-relaxed serif-prose">
                            Provide data-driven real-time financial and technological analysis.
                            In an era of informational overload, our mission is to filter the noise
                            to extract the purest signal for our readers.
                        </p>
                    </section>

                    <section className="space-y-6">
                        <div className="flex items-center gap-3 text-primary mb-2">
                            <Zap size={20} />
                            <h2 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-900 pt-0.5">The Methodology</h2>
                        </div>
                        <p className="text-lg text-gray-600 leading-relaxed serif-prose">
                            We utilize advanced algorithms and artificial intelligence to analyze thousands
                            of global market signals and provide synthetic and actionable reports.
                            Our 24/7 engine scans emerging trends before they become mainstream.
                        </p>
                    </section>
                </div>

                <div className="bg-white border border-gray-100 rounded-3xl p-12 mb-24 shadow-sm">
                    <div className="flex items-center gap-3 text-primary mb-8">
                        <Award size={24} />
                        <h2 className="text-sm font-black uppercase tracking-[0.2em] text-gray-900">Editorial Standards</h2>
                    </div>

                    <div className="prose prose-lg prose-slate max-w-none serif-prose prose-p:text-gray-600">
                        <p>
                            We are committed to data accuracy and objectivity. Every report generated by our AI engine
                            is programmed to respect the highest standards of editorial neutrality.
                            Although our workflow is fully automated, our models are instructed to prioritize
                            verified sources and structured data.
                        </p>
                    </div>
                </div>

                <footer className="pt-12 border-t border-gray-100 flex flex-col items-center text-center">
                    <div className="flex items-center gap-2 text-primary mb-6">
                        <Mail size={20} />
                        <h3 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-900">Reach the Desk</h3>
                    </div>
                    <p className="text-gray-400 text-sm serif italic mb-4">
                        For press inquiries or editorial information:
                    </p>
                    <a
                        href="mailto:stefanovananti@icloud.com"
                        className="text-2xl font-black text-gray-900 hover:text-primary transition-colors border-b-2 border-primary/20 hover:border-primary pb-1"
                    >
                        stefanovananti@icloud.com
                    </a>
                </footer>
            </div>
        </main>
    );
}
