import { FileText } from 'lucide-react';

export default function TermsPage() {
    return (
        <main className="bg-white min-h-screen py-24">
            <div className="max-w-4xl mx-auto px-4">
                <header className="mb-16 border-b border-gray-100 pb-8">
                    <div className="flex items-center gap-3 text-primary mb-4">
                        <FileText size={24} />
                        <span className="text-[10px] font-black uppercase tracking-[0.2em]">Legal Framework</span>
                    </div>
                    <h1 className="text-5xl font-black serif text-gray-900 mb-4">Terms of Service</h1>
                    <p className="text-gray-400 text-xs font-black uppercase tracking-widest">Effective Date: January 1, 2026</p>
                </header>

                <div className="prose prose-xl prose-slate max-w-none serif-prose 
                    prose-headings:text-gray-900 prose-headings:font-black prose-headings:tracking-tighter prose-headings:serif
                    prose-p:text-gray-600 prose-p:leading-relaxed">
                    <h2>1. Acceptance of Terms</h2>
                    <p>
                        By accessing The Capital Sentinel portal, you agree to be bound by these terms.
                        If you do not agree with any part of these terms, you must refrain from using our services.
                    </p>

                    <h2>2. Intellectual Property</h2>
                    <p>
                        All articles, reports, and cinematic images generated by our AI engine are the property of The Capital Sentinel Network. Unauthorized scraping or mass redistribution of our automated intelligence
                        is strictly prohibited.
                    </p>

                    <h2>3. Financial Disclosure</h2>
                    <p>
                        The information provided on this portal, particularly in the Finance and Insurance categories,
                        is for informational purposes only. It does not constitute professional financial or legal advice.
                        Always consult with a qualified professional before making financial decisions.
                    </p>

                    <h2>4. Automated Nature</h2>
                    <p>
                        Users acknowledge that this platform is a "Content Engine" operating on automated trends.
                        System downtime or delays in real-time reporting may occur and do not constitute a breach of service.
                    </p>
                </div>
            </div>
        </main>
    );
}
